version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: today-ok-api-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - db-data:/app/data
    command: npx ts-node -r tsconfig-paths/register src/main.ts
    environment:
      - NODE_ENV=development

volumes:
  db-data:
    driver: local
